### ISSUE TITLE
Regarding LTE jammer

### ISSUE THREAD

**Issue by harshjoshi01** [iamroshanpoudel/SDR#1]
hi, i want to ask that if multiple LTE frequency available than for jam LTE signals we need multiple SDRs? is there any other solution?

i tried frequency hopping method but it is not working.

Thanks.

**Comment by poudelroshan** [comment]
This was a long time ago, but as far as I remember, we had to use 3 SDRs to block the LTE because it kept on hopping between 3 frequencies when one was blocked.
